name: Chatbot Feedback
description: File a bug report.
title: "Chatbot response can be improved"
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: input
    id: conversation_id
    attributes:
      label: Conversation ID
      description: Conversation ID (for internal use)
      placeholder: 00000000-0000-0000-0000-000000000000
    validations:
      required: false
  - type: textarea
    id: ref_docs
    attributes:
      label: Referenced documents
      description: Referenced documents (for internal use)
    validations:
      required: false
  - type: textarea
    id: prompt
    attributes:
      label: Your message
      placeholder: Your message
    validations:
      required: true
  - type: textarea
    id: response
    attributes:
      label: Response to your message
      placeholder: Response to your message
    validations:
      required: true
  - type: dropdown
    id: rate
    attributes:
      label: Please rate the response from 1 to 10
      description: Where is 1 is 'nothing of value in the response' to where 10 is 'the response is perfect'
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
      default: 4
  - type: textarea
    id: desctiption
    attributes:
      label: What did you expect? What was missing from response? What should the response have said?
      description: >-
        A clear and concise explanation for why you think the response was not good. If possible, 
        share exactly what you think the response should have been. 
        If you think it will help, feel free to add screenshots.
      placeholder: Description
    validations:
      required: true

  