---

name: Test1 workflow

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push main image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: refs/heads/main
          fetch-depth: 0
          token: ${{ secrets.ROMARTIN_GIT_ACCESS_TOKEN }}
      - name: Export wisdom service tag
        continue-on-error: false
        run: |
          KUSTOMIZATION_FILE="./assets/kustomization.yaml"
          E0="$(yq '..  | select(has("name")) | select(.name == "*ansible-ai-connect-service")' ${KUSTOMIZATION_FILE})"
          E1="$(sed -n 's/newTag: \(.*\)/\1/p' <<< ${E0})"
          EXPECTED_TAG="$(echo -n ${E1} | sed -e 's/^[[:space:]]*//')"
          echo "EXPECTED_TAG =${EXPECTED_TAG}"
        shell: bash
      - name: Tag Name
        id: tag_name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            sleep 120
            echo "ROGER TEST - BUILD1"

          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "ROGER TEST - BUILD2"

          else
            echo "ROGER TEST - BUILD3"
          fi
